pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://files.minecraftforge.net/maven/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'reactions'

include 'common'
include 'fabric'
include 'fabric-server-relay'
include 'neoforge'
include 'paper-plugin'
