plugins {
    id 'java'
}

base {
    archivesName = "$rootProject.archives_name-paper-plugin-$project.version"
}

tasks.withType(AbstractArchiveTask).configureEach {
    archiveVersion = ''
}

repositories {
    mavenCentral()
    maven {
        name = 'PaperMC'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:$rootProject.paper_api_version"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

processResources {
    inputs.property 'version', project.version

    filesMatching('plugin.yml') {
        expand version: project.version
    }
}
