modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "reactions"
version = "${version}"
displayName = "Reactions"
authors = "Tochuuu"
description = '''A mod that adds dynamic expressions and facial personality to players.'''
#logoFile = ""
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.reactions]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.reactions]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "reactions.mixins.json"
